name: Local App Launcher

on:
  workflow_dispatch:
    inputs:
      action:
        description: Choose what to do
        required: true
        type: choice
        options: [start, stop, restart, status]
      app:
        description: App name (service, process, or compose project)
        required: true
        default: my-app

# Reduce risk: only manual trigger + environment protection
permissions: {}
concurrency: local-app-${{ inputs.app }}

jobs:
  control:
    name: Control ${{ inputs.app }} on local machine
    # Match your runner’s labels, e.g. self-hosted + local-launcher + OS
    runs-on: [self-hosted, local-launcher]
    # Optional: require approval to run
    environment:
      name: local
    timeout-minutes: 10

    steps:
      - name: Echo inputs
        run: |
          echo "Action: ${{ inputs.action }}"
          echo "App: ${{ inputs.app }}"

      - name: Checkout repo (if scripts live here)
        uses: actions/checkout@v4

      # Linux/macOS path
      - name: Execute control script (POSIX)
        if: runner.os != 'Windows'
        run: |
          chmod +x scripts/appctl.sh
          ./scripts/appctl.sh "${{ inputs.app }}" "${{ inputs.action }}"

      # Windows path
      - name: Execute control script (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./scripts/appctl.ps1 -App "${{ inputs.app }}" -Action "${{ inputs.action }}"

      - name: Upload latest logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.app }}-logs"
          path: |
            ${{ runner.os == 'Windows' && 'C:\Users\runneradmin\.local-app-launcher\logs\*' || '~/.local-app-launcher/logs/*' }}
          if-no-files-found: ignore
